version: '3.8'

services:
  ray-head-candidate:
    image: lyon-raycluster:py311-gpu
    container_name: ray-head-candidate
    network_mode: host
    restart: unless-stopped

    volumes:
      - ~/raycluster/workspace:/workspace

    environment:
      - HEAD_MODE=false  # 自動リーダー選出
      - CONSUL_HTTP_ADDR=http://127.0.0.1:8500
      - JUPYTER=yes
      - RAY_memory_monitor_refresh_ms=2500
      - RAY_NODE_HOSTNAME=SET_VPN_HOSTNAME

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
